In [ ]:
import pandas as pd

In [ ]:
pd.set_option('display.max_rows', 10000000000)
pd.set_option('display.max_columns', 100)

In [ ]:
df30 = pd.read_csv("lt30.csv").iloc[:,1:]
df10 = pd.read_csv("lt10.csv").iloc[:,1:]

In [ ]:
df30.sort_values(by=['s'],ascending=False).head(1)

              s        k       r level action
15368472  999.0  29999.0  29.029     g  大壩回四方

In [ ]:
df30.sort_values(by=['k'],ascending=False).head(1)

              s        k       r level action
15368472  999.0  29999.0  29.029     g  大壩回四方

In [ ]:
df30.sort_values(by=['k'],ascending=True).head(1)

      s      k    r level action
0  10.0  100.0  9.0     g  黃河奔快哉

In [ ]:
df30.sort_values(by=['s'],ascending=True).head(1)

      s      k    r level action
0  10.0  100.0  9.0     g  黃河奔快哉

In [ ]:
df10.sort_values(by=['s'],ascending=False).head(1)

             s        k      r level action
5395004  999.0  10988.0  9.999     g  黃河奔快哉

In [ ]:
df10.sort_values(by=['k'],ascending=False).head(1)

             s        k      r level action
5395004  999.0  10988.0  9.999     g  黃河奔快哉

In [ ]:
df10.sort_values(by=['k'],ascending=True).head(1)

      s      k    r level action
0  10.0  100.0  9.0     g  黃河奔快哉

In [ ]:
df10.sort_values(by=['s'],ascending=True).head(1)

      s      k    r level action
0  10.0  100.0  9.0     g  黃河奔快哉

In [ ]:
def a(df):
  print(len(df[df['s']>=10.0][df['s']<100]))
  print(len(df[df['s']>=100.0][df['s']<1000]))

In [ ]:
def b(df):
  print(len(df[df['k']>=100.0][df['k']<1000]))
  print(len(df[df['k']>=1000.0][df['k']<10000]))
  print(len(df[df['k']>=10000.0]))

In [ ]:
a(df30)

143055

<ipython-input-40-d3e8d84edc0c>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df[df['s']>=100.0][df['s']<1000]))

15225418

In [ ]:
b(df30)

882973

<ipython-input-44-bbb964dec2e1>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df[df['k']>=1000.0][df['k']<10000]))

7398725
7086775

In [ ]:
a(df10)

44955

<ipython-input-40-d3e8d84edc0c>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df[df['s']>=100.0][df['s']<1000]))

5350050

In [ ]:
b(df10)

854550

<ipython-input-44-bbb964dec2e1>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df[df['k']>=1000.0][df['k']<10000]))

4495500
44955